version: '3.9'

services:
  web:
    build: .
    container_name: cron-platform
    ports:
      - "8080:8080"
    volumes:
      - ${DATA_DIR}:/app/instance
    environment:
      - FLASK_ENV=production
      # - DISCORD_WEBHOOK_URL=your_webhook_url_here
      # - SESSION_SECRET=a_very_secure_production_secret
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - shared-net

networks:
  shared-net:
    external: true
